[package]
name = "lox"
version = "0.1.0"
edition = "2021"
default-run = "lox"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lox"
path = "src/bin/lox.rs"
test = false

[[bin]]
name = "ast-printer"
path = "src/bin/ast_printer.rs"
test = false

[dependencies]
